SWITCH TO ARCHIVE.

COMPILE FS.KS TO FS.KSM.
COMPILE SYS.KS TO SYS.KSM.
COMPILE EVENT.KS TO EVENT.KSM.
COMPILE MM1.KS TO MM1.KSM.
COMPILE MM2.KS TO MM2.KSM.
COMPILE MM3.KS TO MM3.KSM.
COMPILE MM5.KS TO MM5.KSM.
COMPILE MM6.KS TO MM6.KSM.

COPY FS.KSM TO 1.
COPY SYS.KSM TO 1.
COPY EVENT.KSM TO 1.
COPY MM1.KSM TO 1.
COPY MM2.KSM TO 1.
COPY MM3.KSM TO 1.
COPY MM5.KSM TO 1.
COPY MM6.KSM TO 1.
